apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80 # default is same as targetPort
      nodePort: 30001
  selector:
    app: myapp