apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  labels:
    name: voting-svc
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: voting-pod
    app: voting-app