apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    name: result-svc
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    name: result-pod
    app: voting-app